spring:
  application:
    name: auth-service
  config:
    # dit a spring boot ou aller chercher sa config sur le configServer au démarrage
    import: optional:configserver:http://config-server:8888
  cloud:
    consul:
      host: consul
      port: 8500