server:
  port: 8084

spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:mysql://mysql-menu:3306/${MYSQL_MENU_DB}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: menu-service
        health-check-path: /actuator/health
        health-check-interval: 10s
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

management:
  endpoints:
    web:
      exposure:
        include: "*"